version: "3.8"

services:
  api:
    image: webtronics_app
    command: sh -c "./run.sh && uvicorn api.main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    volumes:
      - ./src:/usr/app/
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres
    env_file: .env
