"""final

Revision ID: 988ad9c660a8
Revises: ba47d86d7a5f
Create Date: 2023-01-08 11:57:27.508600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988ad9c660a8'
down_revision = 'ba47d86d7a5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
