"""likes_and_dislikes

Revision ID: ba47d86d7a5f
Revises: a4b43d750474
Create Date: 2023-01-08 10:22:57.669339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba47d86d7a5f'
down_revision = 'a4b43d750474'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marked_by_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.drop_table('liked_by_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_by_user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], name='liked_by_user_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='liked_by_user_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name='liked_by_user_pkey')
    )
    op.drop_table('marked_by_user')
    # ### end Alembic commands ###
